language: php
sudo: false
php:
  - 7.3
cache:
  directories:
    - "$HOME/.composer/cache/files"
script:
  - php vendor/bin/phpunit tests  --verbose
install:
  - composer install
  - composer dump-autoload
